// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using FriendNotes;
//
//    var userNote = UserNote.FromJson(jsonString);

namespace Friend_Notes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Text;
    using MelonLoader;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public static class UserNotes
    {
        // public static Dictionary<string, UserNote> FromJson(string json) => JsonConvert.DeserializeObject<Dictionary<string, UserNote>>(json, Friend_Notes.Converter.Settings);
        public static Dictionary<string, UserNote> FromFile(FileInfo file) => JsonConvert.DeserializeObject<Dictionary<string, UserNote>>(file.ReadAllText(), Friend_Notes.Converter.Settings);
        public static Dictionary<string, UserNote> FromJson(string json) => JsonConvert.DeserializeObject<Dictionary<string, UserNote>>(json, Friend_Notes.Converter.Settings);
    }

    public partial class UserNote
    {

        [JsonIgnore]
        public string DisplayName { get { return DisplayNames.Last()?.Name; } }

        [JsonIgnore]
        public string FullText { get {
                StringBuilder sb = new StringBuilder();
                if (HasNote) sb.AppendLine(Note);
                if (HasDate) sb.AppendLine(DateAddedText);
                return sb.ToString();
            } }

        [JsonIgnore]
        public bool HasNote { get { return !string.IsNullOrWhiteSpace(Note); } }
        [JsonProperty("Note", NullValueHandling = NullValueHandling.Ignore)]
        public string Note { get; set; }

        [JsonIgnore]
        public bool HasDate { get { return DateAdded != null; } }
        [JsonIgnore]
        public string DateAddedText { get { return HasDate ? "Added: " + DateAdded?.ToString(FriendNotes.dateFormat) : string.Empty; } }
        [JsonProperty("DateAdded", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? DateAdded { get; set; }

        [JsonProperty("DateRequested", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? DateRequested { get; set; }

        [JsonProperty("DisplayNames", NullValueHandling = NullValueHandling.Ignore)]
        public List<DisplayName> DisplayNames { get; set; }


        public UserNote Update(VRC.Player player) => Update(player.field_Private_APIUser_0);
        public UserNote Update(VRC.Core.APIUser user) => Update(user.displayName);
        public UserNote Update(string displayname = null)
        {
            if (displayname != null)
            {
                if (DisplayNames is null) DisplayNames = new List<DisplayName>();
                var names = DisplayNames.Where(f => f.Name == displayname);
                if (names.Count() < 1) DisplayNames.Add(new DisplayName(displayname, DateTime.Now));
                else names.Last().Date = DateTime.Now;
            }
            return this;
        }
    }

    public partial class DisplayName
    {
        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Date", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? Date { get; set; }

        public DisplayName(string name, DateTime date)
        {
            Name = name;
            Date = date;
        }

        public override string ToString()
        {
            return $"\"{Name}\" ({Date})";
        }
    }

    public static partial class Extensions
    {
        /*public static UserNote ByUserId(this IEnumerable<UserNote> list, string uuid) => list.Where(f => f.UserId == uuid).FirstOrDefault();
        public static bool Contains(this IEnumerable<UserNote> list, string uuid) => list.Where(f => f.UserId == uuid).Count() > 0;
        public static void Remove(this Dictionary<string, UserNote> list, string uuid) => list.RemoveAll(f => f.UserId == uuid);*/

        public static UserNote AddPlayer(this Dictionary<string, UserNote> list, VRC.Player player) => list.AddPlayer(player.field_Private_APIUser_0);
        public static UserNote AddPlayer(this Dictionary<string, UserNote> list, VRC.Core.APIUser user) => list.AddPlayer(user.id, user.displayName);
        public static UserNote AddPlayer(this Dictionary<string, UserNote> list, string userid, string displayName = null)
        {
            var player = new UserNote();
            if (displayName != null) player.DisplayNames = new List<DisplayName>() { new DisplayName(displayName, DateTime.Now) };
            list[userid] = player;
            return player;
        }
        public static UserNote AddOrUpdate(this Dictionary<string, UserNote> list, VRC.Player player) => list.AddOrUpdate(player.field_Private_APIUser_0);
        public static UserNote AddOrUpdate(this Dictionary<string, UserNote> list, VRC.Core.APIUser user) => list.AddOrUpdate(user.id, user.displayName);
        public static UserNote AddOrUpdate(this Dictionary<string, UserNote> list, string userid, string displayname = null)
        {
            if (list.ContainsKey(userid)) return list[userid].Update(displayname);
            return list.AddPlayer(userid, displayname);
        }

        public static string ToJson(this Dictionary<string, UserNote> list) => JsonConvert.SerializeObject(list, Friend_Notes.Converter.Settings);
        public static void ToFile(this Dictionary<string, UserNote> list, FileInfo file) => file.WriteAllText(list.ToJson());
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            Formatting = Formatting.Indented
        };
    }
}
