// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using FriendNotes;
//
//    var userNote = UserNote.FromJson(jsonString);

namespace Friend_Notes
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using System.IO;
    using System.Linq;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public static class UserNotes
    {
        public static List<UserNote> FromJson(string json) => JsonConvert.DeserializeObject<List<UserNote>>(json, Friend_Notes.Converter.Settings);
        public static List<UserNote> FromFile(FileInfo file) => JsonConvert.DeserializeObject<List<UserNote>>(file.ReadAllText(), Friend_Notes.Converter.Settings);
    }

    public partial class UserNote
    {

        [JsonProperty("UserId", NullValueHandling = NullValueHandling.Ignore)]
        public string UserId { get; set; }

        [JsonIgnore]
        public string DisplayName { get { return DisplayNames.Count > 0 ? DisplayNames.Last().Name : UserId; } }

        [JsonIgnore]
        public bool HasNote { get { return !string.IsNullOrWhiteSpace(Note); } }
        [JsonProperty("Note", NullValueHandling = NullValueHandling.Ignore)]
        public string Note { get; set; }

        [JsonIgnore]
        public bool HasDate { get { return DateAdded != null; } }
        [JsonIgnore]
        public string DateAddedText { get { return HasDate ? DateAdded?.ToString(FriendNotes.dateFormat) : string.Empty; } }
        [JsonProperty("DateAdded", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? DateAdded { get; set; }

        [JsonProperty("DateRequested", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? DateRequested { get; set; }

        [JsonProperty("DisplayNames", NullValueHandling = NullValueHandling.Ignore)]
        public List<DisplayName> DisplayNames { get; set; }


        public UserNote Update(VRC.Player player) => Update(player.field_Private_APIUser_0);
        public UserNote Update(VRC.Core.APIUser user) => Update(user.displayName);
        public UserNote Update(string displayname = null)
        {
            if (DisplayNames is null) DisplayNames = new List<DisplayName>();
            var names = DisplayNames.Where(f => f.Name == displayname);
            if (names.Count() < 1) DisplayNames.Add(new DisplayName(displayname, DateTime.Now));
            else names.Last().Date = DateTime.Now;
            return this;
        }
    }

    public partial class DisplayName
    {
        [JsonProperty("Name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("Date", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? Date { get; set; }

        public DisplayName(string name, DateTime date)
        {
            Name = name;
            Date = date;
        }

        public override string ToString()
        {
            return $"\"{Name}\" ({Date})";
        }
    }

    public static class Extensions
    {
        public static UserNote ByUserId(this IEnumerable<UserNote> list, string uuid) => list.Where(f => f.UserId == uuid).FirstOrDefault();
        public static bool Contains(this IEnumerable<UserNote> list, string uuid) => list.Where(f => f.UserId == uuid).Count() > 0;
        public static void Remove(this List<UserNote> list, string uuid) => list.RemoveAll(f => f.UserId == uuid);

        public static UserNote AddPlayer(this List<UserNote> list, VRC.Player player) => list.AddPlayer(player.field_Private_APIUser_0);
        public static UserNote AddPlayer(this List<UserNote> list, VRC.Core.APIUser user) => list.AddPlayer(user.id, user.displayName);
        public static UserNote AddPlayer(this List<UserNote> list, string uuid, string displayName) {
            var player = new UserNote() { UserId = uuid, DisplayNames = new List<DisplayName>() { new DisplayName(displayName, DateTime.Now) } };
            list.Add(player);
            return player;
        }
        public static UserNote AddOrUpdate(this List<UserNote> list, VRC.Player player) => list.AddOrUpdate(player.field_Private_APIUser_0);
        public static UserNote AddOrUpdate(this List<UserNote> list, VRC.Core.APIUser user) => list.AddOrUpdate(user.id, user.displayName);
        public static UserNote AddOrUpdate(this List<UserNote> list, string userid, string displayname) {
            var note = list.ByUserId(userid);
            if (note != null) return note.Update(displayname);
            return list.AddPlayer(userid, displayname);
        }

        public static string ToJson(this List<UserNote> list) => JsonConvert.SerializeObject(list, Friend_Notes.Converter.Settings);
        public static void ToFile(this List<UserNote> list, FileInfo file) => file.WriteAllText(list.ToJson());
        public static void WriteAllText(this FileInfo file, string text) => File.WriteAllText(file.FullName, text);
        public static string ReadAllText(this FileInfo file) => File.ReadAllText(file.FullName);
        public static string Quote(this string input) => "\"" + input + "\"";
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            Formatting = Formatting.Indented
        };
    }
}
